export const members = [
  {
    name: 'Yash Karthik',
    cohort: 'Computer Engineering',
    year: 2028,
    siteURL: 'https://www.yashkarthik.xyz',
  },
  {
    name: 'Roozbeh Ali',
    cohort: 'Computer Engineering',
    year: 2028,
    siteURL: 'https://www.roozbehali.me',
  },
  {
    name: 'Sunnie Kapar',
    cohort: 'Computer Engineering',
    year: 2028,
    siteURL: 'https://www.sunniekapar.com',
  },
  {
    name: 'Mark Aagaard',
    cohort: 'Engineering',
    year: null,
    siteURL: 'https://ece.uwaterloo.ca/~maagaard/',
    legacy: 'true',
    status: 'Professor',
  },
  {
    name: 'Nathan Kong',
    cohort: 'Electrical Engineering',
    year: 2028,
    siteURL: 'https://carrizo93.github.io/',
  },
  {
    name: 'Adon Ojha',
    cohort: 'Computer Engineering',
    year: 2028,
    siteURL: 'https://www.adonojha.com',
  },
  {
    name: 'Kaveen Kumarasinghe',
    cohort: 'Computer Engineering',
    year: 2024,
    siteURL: 'https://kaveenk.com',
  },
  {
    name: 'Patrick He',
    cohort: 'Computer Engineering',
    year: 2028,
    siteURL: 'https://www.patrickhe.com',
  },
  {
    name: 'Aryaman Singh',
    cohort: 'Computer Engineering',
    year: 2024,
    siteURL: 'https://www.aryamans.me',
  },
  {
    name: 'Brayden Zhong',
    cohort: 'Electrical Engineering',
    year: 2029,
    siteURL: 'https://www.b8zhong.github.io/',
  },
  {
    name: 'Tazik Shahjahan',
    cohort: 'Computer Engineering',
    year: 2024,
    siteURL: 'https://tazik.sh',
  },
  {
    name: 'Mihir Seth',
    cohort: 'Computer Engineering',
    year: 2028,
    siteURL: 'https://www.mihirseth.com',
  },
  {
    name: 'Akira Yoshiyama',
    cohort: 'Computer Engineering',
    year: 2028,
    siteURL: 'https://ece.uwaterloo.ca/~agyoshiy/',
  },
  {
    name: 'Guhan Iyer',
    cohort: 'Computer Engineering',
    year: 2028,
    siteURL: 'https://guhaniyer.com/',
  },
  {
    name: 'Rongbin Gu',
    cohort: 'Computer Engineering',
    year: 2028,
    siteURL: 'https://rongbin99.github.io/',
  },
  {
    name: 'David Wang',
    cohort: 'Computer Engineering',
    year: 2024,
    siteURL: 'https://enjineerman.github.io/',
  },
];
